spring:
  application:
    name: helper-bot
    description: "REST API for helper-bot"
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN:token}

---
spring:
  config:
    activate:
      on-profile: local

telegram:
  bot:
    token: token

---
spring:
  config:
    activate:
      on-profile: test

telegram:
  bot:
    token: token
